apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nahdi-mw.fullname" . }}
  labels:
    app: {{ include "nahdi-mw.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "nahdi-mw.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "nahdi-mw.name" . }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          env:
            {{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
